spring:
  profiles:
    active: local
  sql:
    init:
      platform: mysql
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3309/parking
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: parking

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: MYSQL
    database-platform: org.hibernate.dialect.MYSQLDialect
#    defer-datasource-initialization: true # (2.5~) Hibernate ??? ?? data.sql ??

---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never